# Generated by Django 5.2.6 on 2025-09-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='idioma',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vaga',
            name='local',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vaga',
            name='salario',
            field=models.CharField(blank=True, help_text='Ex: R$ 3.000 - R$ 4.500', max_length=100, null=True),
        ),
    ]
