# Generated by Django 5.2.5 on 2025-09-25 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vaga_idioma_vaga_local_vaga_salario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='vaga',
            old_name='descricao',
            new_name='descricao_breve',
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='habilidades',
        ),
        migrations.AddField(
            model_name='vaga',
            name='contratante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaga',
            name='descricao_detalhada',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaga',
            name='recomendada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='idioma',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vaga',
            name='local',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vaga',
            name='salario',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vaga',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='ContratanteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contratante_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='vaga',
            name='tags',
            field=models.ManyToManyField(related_name='vagas', to='api.tag'),
        ),
    ]
