# Generated by Django 5.2.5 on 2025-09-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tag_rename_descricao_vaga_descricao_breve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratanteprofile',
            name='contractor_type',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PJ', max_length=2),
        ),
        migrations.AddField(
            model_name='contratanteprofile',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contratanteprofile',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contratanteprofile',
            name='nome_empresa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
