# Generated by Django 5.2.5 on 2025-10-03 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contratanteprofile_contractor_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('aplicante', 'Aplicante'), ('contratante', 'Contratante')], default='aplicante', max_length=20)),
                ('contractor_type', models.CharField(blank=True, choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('nome_empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('especializacoes', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', models.CharField(blank=True, help_text='Tags separadas por vírgula', max_length=255, null=True)),
                ('status', models.CharField(choices=[('Disponível', 'Disponível'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=50)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ContratanteProfile',
        ),
    ]
